### ISSUE TITLE
Bot error

### ISSUE THREAD

**Issue by arynyklas** [BinomTT/bot#1]
Error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "main.py", line 243, in callback_query_handler
    await callback_query.message.delete()
  File "/usr/local/lib/python3.8/dist-packages/aiogram/types/message.py", line 3015, in delete
    return await self.bot.delete_message(self.chat.id, self.message_id)
  File "/usr/local/lib/python3.8/dist-packages/aiogram/bot/bot.py", line 2950, in delete_message
    return await self.request(api.Methods.DELETE_MESSAGE, payload)
  File "/usr/local/lib/python3.8/dist-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/usr/local/lib/python3.8/dist-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/usr/local/lib/python3.8/dist-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/usr/local/lib/python3.8/dist-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.MessageCantBeDeleted: Message can't be deleted for everyone
```

Update:
```
{"update_id": -1, "callback_query": {"id": "-1", "from": {"id": -1, "is_bot": false, "first_name": "", "username": "", "language_code": "ru"}, "message": {"message_id": -1, "from": {"id": 5550072220, "is_bot": true, "first_name": "Binom TimeTable Bot", "username": "BinomTTBot"}, "chat": {"id": -1, "first_name": "", "username": "", "type": "private"}, "date": 1676731157, "text": "Привет!\nЯ даю расписания для всех классов.\nВыберите Ваш класс:", "reply_markup": {"inline_keyboard": [[{"text": "5 А", "callback_data": "timetable_class_*93_82"}, {"text": "5 Ә", "callback_data": "timetable_class_*94_82"}], [{"text": "5 Б", "callback_data": "timetable_class_*95_82"}, {"text": "5 В", "callback_data": "timetable_class_*96_82"}], [{"text": "5 Г", "callback_data": "timetable_class_*97_82"}, {"text": "5 Ғ", "callback_data": "timetable_class_*98_82"}], [{"text": "5 Д", "callback_data": "timetable_class_*99_82"}, {"text": "5 Е", "callback_data": "timetable_class_*100_82"}], [{"text": "5 Ж", "callback_data": "timetable_class_*101_82"}, {"text": "5 З", "callback_data": "timetable_class_*102_82"}], [{"text": "5 И", "callback_data": "timetable_class_*103_82"}, {"text": "5 К", "callback_data": "timetable_class_*104_82"}], [{"text": "5 Қ", "callback_data": "timetable_class_*105_82"}, {"text": "5 Л", "callback_data": "timetable_class_*106_82"}], [{"text": "5 М", "callback_data": "timetable_class_*107_82"}, {"text": "5 Н", "callback_data": "timetable_class_*108_82"}], [{"text": "6 А", "callback_data": "timetable_class_*50_82"}, {"text": "6 Ә", "callback_data": "timetable_class_*51_82"}], [{"text": "6 Б", "callback_data": "timetable_class_*52_82"}, {"text": "6 В", "callback_data": "timetable_class_*53_82"}], [{"text": "➡️", "callback_data": "timetable_page_1"}], [{"text": "Свободные кабинеты", "callback_data": "classrooms_free"}]]}}, "chat_instance": "-1", "data": "timetable_class_*53_82"}}
```

**Comment by arynyklas** [comment]
Fixed.
